### ISSUE TITLE
Deserialize component problems

### ISSUE THREAD

**Issue by mrvir** [pravdomil/React-Serialize#2]
It throw 'Deserialization error: element type must be string' when I deserialize JSON like this:
```
     {
      "props": {
        "style": {
          "fontSize": "20px",
          "color": "#c00"
        },
        "type": "close",
        "theme": "outlined"
      }
```
The original component: `<Icon style={{ fontSize: '20px', color: '#c00' }} type="close" theme="outlined" />`

**Comment by pravdomil** [comment]
`type` is not part of `props`, there is `{ type: string, props: {} }`

<img width="124" alt="image" src="https://user-images.githubusercontent.com/2387356/47260515-626cb900-d4bd-11e8-804a-d13cfc39a941.png">
